### ISSUE TITLE
Room has no id bread Room.findAll

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty-puppet#4]
```shell
00:26:34 VERB Room findAll() rejected: no id
Error: no id
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet/src/puppet.ts:850:13)
    at Generator.next (<anonymous>)
    at /wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadchat.roomPayload (/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js:510:16)
    at AnotherOriginalClass.<anonymous> (/wechaty/src/user/room.ts:293:23)
    at Generator.next (<anonymous>)
    at /wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.ready (/wechaty/dist/src/user/room.js:241:16)
    at Promise.all.roomList.map.room (/wechaty/src/user/room.ts:128:27)
    at Array.map (<anonymous>)
    at Function.<anonymous> (/wechaty/src/user/room.ts:125:18)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/user/room.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Exception is thrown out when trying to get all the room payload. I think issue should be here:
https://github.com/Chatie/wechaty-puppet/blob/5b24558cc24fe1fc30178820467a7ffc41b047ea/src/puppet.ts#L829-L833

The id might be `undefined` or `null`, so in `roomPayload` function the error thrown out:
https://github.com/Chatie/wechaty-puppet/blob/5b24558cc24fe1fc30178820467a7ffc41b047ea/src/puppet.ts#L935-L942

Comparing to `contactSearch`
https://github.com/Chatie/wechaty-puppet/blob/5b24558cc24fe1fc30178820467a7ffc41b047ea/src/puppet.ts#L491-L507

I think we should do similar things for room, when error happens, catch it and log it, but not throw exception that breaks the whole process. 

Does this make sense to you @zixia ?

**Comment by zixia** [comment]
Yes, I feel this does make sense for me.
